import type { SportEvent } from "@/lib/types";
import { getTeam } from "./teams";
import { getCompetition } from "./competitions";
import { daysFromNow, hoursFromNow } from "./helpers";

function participant(teamId: string, score?: number) {
  return { team: getTeam(teamId), score };
}

export const EVENTS: SportEvent[] = [
  // ---------------------------------------------------------------- Football
  {
    id: "evt-football-1",
    slug: "sterling-fc-vs-vantage-athletic",
    sport: "football",
    competition: getCompetition("comp-football-1"),
    status: "finished",
    startTime: daysFromNow(-3, 19, 0),
    home: participant("team-football-3", 2),
    away: participant("team-football-4", 1),
    venue: "Sterling Park",
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-football-2",
    slug: "iron-coast-sc-vs-meridian-city",
    sport: "football",
    competition: getCompetition("comp-football-1"),
    status: "finished",
    startTime: hoursFromNow(-1),
    home: participant("team-football-5", 1),
    away: participant("team-football-6", 0),
    venue: "Coastal Arena",
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-football-featured",
    slug: "northbridge-united-vs-real-alcazar",
    sport: "football",
    competition: getCompetition("comp-football-1"),
    status: "scheduled",
    startTime: daysFromNow(3, 19, 30),
    home: participant("team-football-1"),
    away: participant("team-football-2"),
    venue: "Northbridge Arena",
    hasIntelligence: true,
    hasPrediction: true,
    isPopular: true,
  },
  {
    id: "evt-football-4",
    slug: "sterling-fc-vs-iron-coast-sc",
    sport: "football",
    competition: getCompetition("comp-football-1"),
    status: "scheduled",
    startTime: daysFromNow(6, 17, 0),
    home: participant("team-football-3"),
    away: participant("team-football-5"),
    venue: "Sterling Park",
    hasIntelligence: true,
    hasPrediction: true,
  },
  {
    id: "evt-football-5",
    slug: "vantage-athletic-vs-meridian-city",
    sport: "football",
    competition: getCompetition("comp-football-1"),
    status: "finished",
    startTime: daysFromNow(-5, 20, 0),
    home: participant("team-football-4", 1),
    away: participant("team-football-6", 1),
    venue: "Vantage Ground",
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-football-6",
    slug: "real-alcazar-vs-vantage-athletic",
    sport: "football",
    competition: getCompetition("comp-football-1"),
    status: "scheduled",
    startTime: daysFromNow(8, 19, 0),
    home: participant("team-football-2"),
    away: participant("team-football-4"),
    venue: "Alcazar Stadium",
    hasIntelligence: true,
    hasPrediction: true,
  },
  {
    id: "evt-football-7",
    slug: "meridian-city-vs-sterling-fc",
    sport: "football",
    competition: getCompetition("comp-football-1"),
    status: "scheduled",
    startTime: daysFromNow(9, 17, 30),
    home: participant("team-football-6"),
    away: participant("team-football-3"),
    venue: "Meridian Arena",
    hasIntelligence: true,
    hasPrediction: true,
    isPopular: true,
  },

  // ------------------------------------------------------------------ Hockey
  {
    id: "evt-hockey-1",
    slug: "frost-wolves-vs-steel-bears",
    sport: "hockey",
    competition: getCompetition("comp-hockey-1"),
    status: "finished",
    startTime: daysFromNow(-2, 19, 0),
    home: participant("team-hockey-1", 4),
    away: participant("team-hockey-2", 3),
    venue: "Frostline Arena",
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-hockey-2",
    slug: "arctic-kings-vs-redline-hc",
    sport: "hockey",
    competition: getCompetition("comp-hockey-1"),
    status: "scheduled",
    startTime: daysFromNow(2, 18, 30),
    home: participant("team-hockey-3"),
    away: participant("team-hockey-4"),
    venue: "Kings Ice Hall",
    hasIntelligence: true,
    hasPrediction: true,
  },
  {
    id: "evt-hockey-3",
    slug: "steel-bears-vs-arctic-kings",
    sport: "hockey",
    competition: getCompetition("comp-hockey-1"),
    status: "scheduled",
    startTime: daysFromNow(5, 19, 0),
    home: participant("team-hockey-2"),
    away: participant("team-hockey-3"),
    venue: "Steel Dome",
    hasIntelligence: true,
    hasPrediction: true,
    isPopular: true,
  },
  {
    id: "evt-hockey-4",
    slug: "redline-hc-vs-southern-comets",
    sport: "hockey",
    competition: getCompetition("comp-hockey-1"),
    status: "finished",
    startTime: hoursFromNow(-1),
    home: participant("team-hockey-4", 2),
    away: participant("team-hockey-5", 2),
    venue: "Redline Arena",
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-hockey-5",
    slug: "vulcan-reign-vs-frost-wolves",
    sport: "hockey",
    competition: getCompetition("comp-hockey-1"),
    status: "finished",
    startTime: daysFromNow(-4, 19, 0),
    home: participant("team-hockey-6", 3),
    away: participant("team-hockey-1", 5),
    venue: "Vulcan Hall",
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-hockey-6",
    slug: "southern-comets-vs-vulcan-reign",
    sport: "hockey",
    competition: getCompetition("comp-hockey-1"),
    status: "scheduled",
    startTime: daysFromNow(3, 18, 0),
    home: participant("team-hockey-5"),
    away: participant("team-hockey-6"),
    venue: "Comet Bay Arena",
    hasIntelligence: true,
    hasPrediction: true,
  },
  {
    id: "evt-hockey-7",
    slug: "frost-wolves-vs-redline-hc",
    sport: "hockey",
    competition: getCompetition("comp-hockey-1"),
    status: "scheduled",
    startTime: daysFromNow(7, 19, 30),
    home: participant("team-hockey-1"),
    away: participant("team-hockey-4"),
    venue: "Frostline Arena",
    hasIntelligence: true,
    hasPrediction: true,
  },

  // ------------------------------------------------------------------ Tennis
  {
    id: "evt-tennis-1",
    slug: "d-volkov-vs-m-ferreira",
    sport: "tennis",
    competition: getCompetition("comp-tennis-1"),
    status: "finished",
    startTime: daysFromNow(-4, 14, 0),
    home: participant("team-tennis-1", 2),
    away: participant("team-tennis-2", 0),
    venue: "Grand Circuit Court 1",
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-tennis-2",
    slug: "a-takahashi-vs-j-okafor",
    sport: "tennis",
    competition: getCompetition("comp-tennis-1"),
    status: "scheduled",
    startTime: daysFromNow(1, 13, 0),
    home: participant("team-tennis-3"),
    away: participant("team-tennis-4"),
    venue: "Grand Circuit Court 2",
    hasIntelligence: true,
    hasPrediction: true,
  },
  {
    id: "evt-tennis-3",
    slug: "d-volkov-vs-a-takahashi",
    sport: "tennis",
    competition: getCompetition("comp-tennis-1"),
    status: "scheduled",
    startTime: daysFromNow(4, 15, 0),
    home: participant("team-tennis-1"),
    away: participant("team-tennis-3"),
    venue: "Grand Circuit Centre Court",
    hasIntelligence: true,
    hasPrediction: true,
    isPopular: true,
  },
  {
    id: "evt-tennis-4",
    slug: "m-ferreira-vs-j-okafor",
    sport: "tennis",
    competition: getCompetition("comp-tennis-1"),
    status: "finished",
    startTime: daysFromNow(-6, 14, 0),
    home: participant("team-tennis-2", 2),
    away: participant("team-tennis-4", 1),
    venue: "Grand Circuit Court 3",
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-tennis-5",
    slug: "l-andersson-vs-r-costa",
    sport: "tennis",
    competition: getCompetition("comp-tennis-1"),
    status: "scheduled",
    startTime: daysFromNow(2, 12, 0),
    home: participant("team-tennis-5"),
    away: participant("team-tennis-6"),
    venue: "Grand Circuit Court 1",
    hasIntelligence: true,
    hasPrediction: true,
  },
  {
    id: "evt-tennis-6",
    slug: "m-ferreira-vs-l-andersson",
    sport: "tennis",
    competition: getCompetition("comp-tennis-1"),
    status: "scheduled",
    startTime: daysFromNow(5, 13, 30),
    home: participant("team-tennis-2"),
    away: participant("team-tennis-5"),
    venue: "Grand Circuit Court 2",
    hasIntelligence: true,
    hasPrediction: true,
  },
  {
    id: "evt-tennis-7",
    slug: "r-costa-vs-j-okafor",
    sport: "tennis",
    competition: getCompetition("comp-tennis-1"),
    status: "scheduled",
    startTime: daysFromNow(6, 16, 0),
    home: participant("team-tennis-6"),
    away: participant("team-tennis-4"),
    venue: "Grand Circuit Court 3",
    hasIntelligence: true,
    hasPrediction: true,
  },

  // --------------------------------------------------------------------- CS2
  {
    id: "evt-cs2-1",
    slug: "nova-sentinel-vs-obsidian-five",
    sport: "cs2",
    competition: getCompetition("comp-cs2-1"),
    status: "finished",
    startTime: daysFromNow(-3, 17, 0),
    home: participant("team-cs2-1", 2),
    away: participant("team-cs2-2", 1),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-cs2-2",
    slug: "vertex-gaming-vs-crimson-wolves",
    sport: "cs2",
    competition: getCompetition("comp-cs2-1"),
    status: "finished",
    startTime: hoursFromNow(-1),
    home: participant("team-cs2-3", 8),
    away: participant("team-cs2-4", 6),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-cs2-3",
    slug: "nova-sentinel-vs-vertex-gaming",
    sport: "cs2",
    competition: getCompetition("comp-cs2-1"),
    status: "scheduled",
    startTime: daysFromNow(5, 18, 0),
    home: participant("team-cs2-1"),
    away: participant("team-cs2-3"),
    hasIntelligence: true,
    hasPrediction: true,
    isPopular: true,
  },
  {
    id: "evt-cs2-4",
    slug: "obsidian-five-vs-crimson-wolves",
    sport: "cs2",
    competition: getCompetition("comp-cs2-1"),
    status: "finished",
    startTime: daysFromNow(-4, 17, 0),
    home: participant("team-cs2-2", 1),
    away: participant("team-cs2-4", 2),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-cs2-5",
    slug: "phantom-six-vs-iron-sight",
    sport: "cs2",
    competition: getCompetition("comp-cs2-1"),
    status: "scheduled",
    startTime: daysFromNow(3, 15, 0),
    home: participant("team-cs2-5"),
    away: participant("team-cs2-6"),
    hasIntelligence: true,
    hasPrediction: true,
  },
  {
    id: "evt-cs2-6",
    slug: "nova-sentinel-vs-phantom-six",
    sport: "cs2",
    competition: getCompetition("comp-cs2-1"),
    status: "scheduled",
    startTime: daysFromNow(6, 16, 30),
    home: participant("team-cs2-1"),
    away: participant("team-cs2-5"),
    hasIntelligence: true,
    hasPrediction: true,
  },
  {
    id: "evt-cs2-7",
    slug: "crimson-wolves-vs-iron-sight",
    sport: "cs2",
    competition: getCompetition("comp-cs2-1"),
    status: "scheduled",
    startTime: daysFromNow(7, 18, 0),
    home: participant("team-cs2-4"),
    away: participant("team-cs2-6"),
    hasIntelligence: true,
    hasPrediction: true,
  },

  // ------------------------------------------------------------------ Dota 2
  {
    id: "evt-dota-2-1",
    slug: "ember-guard-vs-shadow-circuit",
    sport: "dota-2",
    competition: getCompetition("comp-dota-2-1"),
    status: "finished",
    startTime: daysFromNow(-2, 15, 0),
    home: participant("team-dota-2-1", 2),
    away: participant("team-dota-2-2", 0),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-dota-2-2",
    slug: "titan-forge-vs-null-pointer",
    sport: "dota-2",
    competition: getCompetition("comp-dota-2-1"),
    status: "finished",
    startTime: hoursFromNow(-1),
    home: participant("team-dota-2-3", 18),
    away: participant("team-dota-2-4", 22),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-dota-2-3",
    slug: "ember-guard-vs-titan-forge",
    sport: "dota-2",
    competition: getCompetition("comp-dota-2-1"),
    status: "scheduled",
    startTime: daysFromNow(6, 15, 0),
    home: participant("team-dota-2-1"),
    away: participant("team-dota-2-3"),
    hasIntelligence: true,
    hasPrediction: true,
    isPopular: true,
  },
  {
    id: "evt-dota-2-4",
    slug: "shadow-circuit-vs-null-pointer",
    sport: "dota-2",
    competition: getCompetition("comp-dota-2-1"),
    status: "finished",
    startTime: daysFromNow(-3, 15, 0),
    home: participant("team-dota-2-2", 0),
    away: participant("team-dota-2-4", 2),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-dota-2-5",
    slug: "void-legion-vs-ashen-pact",
    sport: "dota-2",
    competition: getCompetition("comp-dota-2-1"),
    status: "scheduled",
    startTime: daysFromNow(2, 17, 0),
    home: participant("team-dota-2-5"),
    away: participant("team-dota-2-6"),
    hasIntelligence: true,
    hasPrediction: true,
  },
  {
    id: "evt-dota-2-6",
    slug: "ember-guard-vs-void-legion",
    sport: "dota-2",
    competition: getCompetition("comp-dota-2-1"),
    status: "scheduled",
    startTime: daysFromNow(5, 16, 0),
    home: participant("team-dota-2-1"),
    away: participant("team-dota-2-5"),
    hasIntelligence: true,
    hasPrediction: true,
  },
  {
    id: "evt-dota-2-7",
    slug: "null-pointer-vs-ashen-pact",
    sport: "dota-2",
    competition: getCompetition("comp-dota-2-1"),
    status: "scheduled",
    startTime: daysFromNow(7, 15, 30),
    home: participant("team-dota-2-4"),
    away: participant("team-dota-2-6"),
    hasIntelligence: true,
    hasPrediction: true,
  },

  // ---------------------------------------------------------- Mobile Legends
  {
    id: "evt-mlbb-1",
    slug: "solar-flare-vs-rapid-fang",
    sport: "mobile-legends",
    competition: getCompetition("comp-mlbb-1"),
    status: "finished",
    startTime: daysFromNow(-1, 12, 0),
    home: participant("team-mlbb-1", 2),
    away: participant("team-mlbb-2", 1),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-mlbb-2",
    slug: "golden-spire-vs-nightfall-squad",
    sport: "mobile-legends",
    competition: getCompetition("comp-mlbb-1"),
    status: "finished",
    startTime: hoursFromNow(-1),
    home: participant("team-mlbb-3", 6),
    away: participant("team-mlbb-4", 9),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-mlbb-3",
    slug: "solar-flare-vs-golden-spire",
    sport: "mobile-legends",
    competition: getCompetition("comp-mlbb-1"),
    status: "scheduled",
    startTime: daysFromNow(4, 14, 0),
    home: participant("team-mlbb-1"),
    away: participant("team-mlbb-3"),
    hasIntelligence: true,
    hasPrediction: true,
    isPopular: true,
  },
  {
    id: "evt-mlbb-4",
    slug: "rapid-fang-vs-nightfall-squad",
    sport: "mobile-legends",
    competition: getCompetition("comp-mlbb-1"),
    status: "finished",
    startTime: daysFromNow(-2, 12, 0),
    home: participant("team-mlbb-2", 1),
    away: participant("team-mlbb-4", 2),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-mlbb-5",
    slug: "crimson-tide-vs-storm-vanguard",
    sport: "mobile-legends",
    competition: getCompetition("comp-mlbb-1"),
    status: "scheduled",
    startTime: daysFromNow(2, 11, 0),
    home: participant("team-mlbb-5"),
    away: participant("team-mlbb-6"),
    hasIntelligence: true,
    hasPrediction: true,
  },
  {
    id: "evt-mlbb-6",
    slug: "solar-flare-vs-crimson-tide",
    sport: "mobile-legends",
    competition: getCompetition("comp-mlbb-1"),
    status: "scheduled",
    startTime: daysFromNow(5, 13, 0),
    home: participant("team-mlbb-1"),
    away: participant("team-mlbb-5"),
    hasIntelligence: true,
    hasPrediction: true,
  },
  {
    id: "evt-mlbb-7",
    slug: "nightfall-squad-vs-storm-vanguard",
    sport: "mobile-legends",
    competition: getCompetition("comp-mlbb-1"),
    status: "scheduled",
    startTime: daysFromNow(6, 12, 30),
    home: participant("team-mlbb-4"),
    away: participant("team-mlbb-6"),
    hasIntelligence: true,
    hasPrediction: true,
  },

  // --------------------------------------------------------------------------- UFC
  {
    id: "evt-ufc-1",
    slug: "dominic-vance-vs-elias-marchetti",
    sport: "ufc",
    competition: getCompetition("comp-ufc-1"),
    status: "finished",
    startTime: daysFromNow(-2, 22, 0),
    home: participant("team-ufc-1", 1),
    away: participant("team-ufc-2", 0),
    venue: "Ironclad Arena",
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-ufc-2",
    slug: "kenji-osei-vs-viktor-zima",
    sport: "ufc",
    competition: getCompetition("comp-ufc-1"),
    status: "finished",
    startTime: daysFromNow(-4, 21, 0),
    home: participant("team-ufc-3", 0),
    away: participant("team-ufc-4", 1),
    venue: "Kestrel Combat Center",
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-ufc-3",
    slug: "dominic-vance-vs-kenji-osei",
    sport: "ufc",
    competition: getCompetition("comp-ufc-1"),
    status: "scheduled",
    startTime: daysFromNow(4, 22, 0),
    home: participant("team-ufc-1"),
    away: participant("team-ufc-3"),
    venue: "Meridia Fight Arena",
    hasIntelligence: true,
    hasPrediction: true,
    isPopular: true,
  },
  {
    id: "evt-ufc-4",
    slug: "elias-marchetti-vs-viktor-zima",
    sport: "ufc",
    competition: getCompetition("comp-ufc-1"),
    status: "finished",
    startTime: daysFromNow(-6, 21, 30),
    home: participant("team-ufc-2", 1),
    away: participant("team-ufc-4", 0),
    venue: "Astoria Octagon Center",
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-ufc-5",
    slug: "tyrell-banks-vs-rocco-salvatore",
    sport: "ufc",
    competition: getCompetition("comp-ufc-1"),
    status: "scheduled",
    startTime: daysFromNow(3, 22, 0),
    home: participant("team-ufc-5"),
    away: participant("team-ufc-6"),
    venue: "Valeria Arena",
    hasIntelligence: true,
    hasPrediction: true,
  },
  {
    id: "evt-ufc-6",
    slug: "dominic-vance-vs-tyrell-banks",
    sport: "ufc",
    competition: getCompetition("comp-ufc-1"),
    status: "scheduled",
    startTime: daysFromNow(7, 21, 30),
    home: participant("team-ufc-1"),
    away: participant("team-ufc-5"),
    venue: "Ironclad Arena",
    hasIntelligence: true,
    hasPrediction: true,
  },
  {
    id: "evt-ufc-7",
    slug: "viktor-zima-vs-rocco-salvatore",
    sport: "ufc",
    competition: getCompetition("comp-ufc-1"),
    status: "scheduled",
    startTime: daysFromNow(8, 22, 0),
    home: participant("team-ufc-4"),
    away: participant("team-ufc-6"),
    venue: "Meridia Fight Arena",
    hasIntelligence: true,
    hasPrediction: true,
  },

  // --------------------------------------------------------------------
  // Historical head-to-head backfill. These are older *finished* matches
  // between pairs that also meet in an upcoming/live event above — they
  // exist only so getHeadToHeadEvents() has real data to aggregate for
  // the "team comparison" block, and their tallies are written to agree
  // with the head-to-head claims already made in predictions.ts /
  // event-statistics.ts (e.g. "Volkov ведёт 3-1"). They're old enough
  // (60+ days back) that they never show up in a "recent results" list
  // limited to the last few matches.
  // --------------------------------------------------------------------
  {
    id: "evt-football-h2h-1",
    slug: "northbridge-united-vs-real-alcazar-h2h-1",
    sport: "football",
    competition: getCompetition("comp-football-1"),
    status: "finished",
    startTime: daysFromNow(-60, 19, 0),
    home: participant("team-football-1", 2),
    away: participant("team-football-2", 1),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-football-h2h-2",
    slug: "real-alcazar-vs-northbridge-united-h2h-2",
    sport: "football",
    competition: getCompetition("comp-football-1"),
    status: "finished",
    startTime: daysFromNow(-150, 19, 0),
    home: participant("team-football-2", 1),
    away: participant("team-football-1", 1),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-football-h2h-3",
    slug: "northbridge-united-vs-real-alcazar-h2h-3",
    sport: "football",
    competition: getCompetition("comp-football-1"),
    status: "finished",
    startTime: daysFromNow(-240, 19, 0),
    home: participant("team-football-1", 0),
    away: participant("team-football-2", 0),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-football-h2h-4",
    slug: "real-alcazar-vs-northbridge-united-h2h-4",
    sport: "football",
    competition: getCompetition("comp-football-1"),
    status: "finished",
    startTime: daysFromNow(-330, 19, 0),
    home: participant("team-football-2", 2),
    away: participant("team-football-1", 0),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-football-h2h-5",
    slug: "northbridge-united-vs-real-alcazar-h2h-5",
    sport: "football",
    competition: getCompetition("comp-football-1"),
    status: "finished",
    startTime: daysFromNow(-420, 19, 0),
    home: participant("team-football-1", 3),
    away: participant("team-football-2", 1),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-hockey-h2h-1",
    slug: "steel-bears-vs-arctic-kings-h2h-1",
    sport: "hockey",
    competition: getCompetition("comp-hockey-1"),
    status: "finished",
    startTime: daysFromNow(-70, 19, 0),
    home: participant("team-hockey-2", 4),
    away: participant("team-hockey-3", 3),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-hockey-h2h-2",
    slug: "arctic-kings-vs-steel-bears-h2h-2",
    sport: "hockey",
    competition: getCompetition("comp-hockey-1"),
    status: "finished",
    startTime: daysFromNow(-160, 19, 0),
    home: participant("team-hockey-3", 4),
    away: participant("team-hockey-2", 3),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-hockey-h2h-3",
    slug: "steel-bears-vs-arctic-kings-h2h-3",
    sport: "hockey",
    competition: getCompetition("comp-hockey-1"),
    status: "finished",
    startTime: daysFromNow(-250, 19, 0),
    home: participant("team-hockey-2", 3),
    away: participant("team-hockey-3", 2),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-hockey-h2h-4",
    slug: "arctic-kings-vs-steel-bears-h2h-4",
    sport: "hockey",
    competition: getCompetition("comp-hockey-1"),
    status: "finished",
    startTime: daysFromNow(-340, 19, 0),
    home: participant("team-hockey-3", 5),
    away: participant("team-hockey-2", 4),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-tennis-h2h-1",
    slug: "d-volkov-vs-a-takahashi-h2h-1",
    sport: "tennis",
    competition: getCompetition("comp-tennis-1"),
    status: "finished",
    startTime: daysFromNow(-80, 14, 0),
    home: participant("team-tennis-1", 2),
    away: participant("team-tennis-3", 1),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-tennis-h2h-2",
    slug: "a-takahashi-vs-d-volkov-h2h-2",
    sport: "tennis",
    competition: getCompetition("comp-tennis-1"),
    status: "finished",
    startTime: daysFromNow(-170, 14, 0),
    home: participant("team-tennis-3", 2),
    away: participant("team-tennis-1", 0),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-tennis-h2h-3",
    slug: "d-volkov-vs-a-takahashi-h2h-3",
    sport: "tennis",
    competition: getCompetition("comp-tennis-1"),
    status: "finished",
    startTime: daysFromNow(-260, 14, 0),
    home: participant("team-tennis-1", 2),
    away: participant("team-tennis-3", 0),
    hasIntelligence: false,
    hasPrediction: false,
  },
  {
    id: "evt-tennis-h2h-4",
    slug: "d-volkov-vs-a-takahashi-h2h-4",
    sport: "tennis",
    competition: getCompetition("comp-tennis-1"),
    status: "finished",
    startTime: daysFromNow(-350, 14, 0),
    home: participant("team-tennis-1", 2),
    away: participant("team-tennis-3", 1),
    hasIntelligence: false,
    hasPrediction: false,
  },
];

/** Every event involving this team, either side, across every status —
 * most recent first. The team page splits this into live/upcoming/
 * finished groups itself, the same way sport.service.ts already does
 * for a whole sport. */
export function getEventsByTeam(teamId: string): SportEvent[] {
  return EVENTS.filter((e) => e.home.team.id === teamId || e.away.team.id === teamId).sort(
    (a, b) => new Date(b.startTime).getTime() - new Date(a.startTime).getTime()
  );
}

export function getHeadToHeadEvents(
  teamAId: string,
  teamBId: string,
  excludeEventId?: string
): SportEvent[] {
  return EVENTS.filter(
    (e) =>
      e.status === "finished" &&
      e.id !== excludeEventId &&
      ((e.home.team.id === teamAId && e.away.team.id === teamBId) ||
        (e.home.team.id === teamBId && e.away.team.id === teamAId))
  ).sort((a, b) => new Date(b.startTime).getTime() - new Date(a.startTime).getTime());
}

export function getEventBySlug(sport: string, slug: string): SportEvent | undefined {
  return EVENTS.find((e) => e.sport === sport && e.slug === slug);
}

export function getEventsBySport(sport: string): SportEvent[] {
  return EVENTS.filter((e) => e.sport === sport);
}

export function getUpcomingEvents(limit?: number): SportEvent[] {
  const upcoming = EVENTS.filter((e) => e.status === "scheduled").sort(
    (a, b) => new Date(a.startTime).getTime() - new Date(b.startTime).getTime()
  );
  return limit ? upcoming.slice(0, limit) : upcoming;
}

export function getRecentResults(sport?: string, limit?: number): SportEvent[] {
  const finished = EVENTS.filter(
    (e) => e.status === "finished" && (!sport || e.sport === sport)
  ).sort((a, b) => new Date(b.startTime).getTime() - new Date(a.startTime).getTime());
  return limit ? finished.slice(0, limit) : finished;
}

export function getPopularEvents(limit?: number): SportEvent[] {
  const popular = EVENTS.filter((e) => e.isPopular);
  return limit ? popular.slice(0, limit) : popular;
}
