// AUTO-GENERATED by scripts/fetch-real-events.mjs at build time — do not edit by hand.
// Real football + hockey fixtures/results fetched from football-data.org and the
// NHL's public schedule API. Falls back to empty arrays when a fetch fails or the
// FOOTBALL_DATA_API_TOKEN secret is missing, so the build never breaks because of it.

import type { SportEvent, Team, Competition } from "@/lib/types";

export const REAL_EVENTS: SportEvent[] = [];

export const REAL_TEAMS: Team[] = [];

export const REAL_COMPETITIONS: Competition[] = [];
